# This file serves as an example to explain various configuration parameters for
# Godoc-Lint.
#
# All keys are:
#  - Optional, unless stated otherwise.
#  - Assigned with their default value.
#

# Configuration file version.
version: "1.0"

# List of regexp patterns matching files the linter should include. When
# omitted/null, the linter includes all Go files. If assigned then only the
# files that their relative path (with respect to the config file path) matches
# any of the patterns will be processed.
#
# NOTE: The patterns must assume a Unix-like path (i.e., separated with forward
# slashes, `/`), even on Windows. This is to ensure a consistent behavior across
# different platforms.
#
# Example:
#   include:
#     - ^pkg/
#     - _foo.go$
include: null

# List of regexp patterns matching files the linter should skip. When
# omitted/null, the linter excludes no Go files. If assigned then only the
# files that their relative path (with respect to the config file path) does not
# match any of the patterns will be processed.
#
# NOTE: The patterns must assume a Unix-like path (i.e., separated with forward
# slashes, `/`), even on Windows. This is to ensure a consistent behavior across
# different platforms.
#
# Example:
#   exclude:
#     - ^internal/
#     - _autogenerated.go$
exclude: null

# List of rules to enable.
#
# See the linter docs for the list of supported rules.
enable:
  - pkg-doc
  - single-pkg-doc
  - start-with-name

# List of rules to disable.
#
# Example:
#   disable:
#     - pkg-doc
#     - single-pkg-doc
disable: null

# A map for setting individual rule options.
#
# All sub-keys are optional.
options:
  # Maximum line length for godocs, not including the `// `, or `/*` or `*/`
  # tokens.
  max-len/length: 77

  # Include test files when applying the `max-len` rule.
  max-len/include-tests: false

  # The start of a valid package godoc (e.g., "Package <NAME>...").
  pkg-doc/start-with: Package

  # Include test files when applying the `pkg-doc` rule.
  pkg-doc/include-tests: false

  # Include test files when applying the `single-pkg-doc` rule.
  single-pkg-doc/include-tests: false

  # Include test files when applying the `require-pkg-doc` rule.
  require-pkg-doc/include-tests: false

  # Include test files when applying the `require-doc` rule.
  require-doc/include-tests: false

  # Ignore exported (public) symbols when applying the `require-doc` rule.
  require-doc/ignore-exported: false

  # Ignore unexported (private) symbols when applying the `require-doc` rule.
  require-doc/ignore-unexported: true

  # Include test files when applying the `start-with-name` rule.
  start-with-name/include-tests: false

  # Include unexported (private) symbols when applying the `start-with-name` rule.
  start-with-name/include-unexported: false

  # Acceptable start pattern (regexp) for godocs when applying the
  # `start-with-name` rule. The `%` placeholder is where the corresponding
  # symbol name should appear. An omitted placeholder means the symbol
  # name should appear at the end of the pattern.
  start-with-name/pattern: "((A|a|An|an|THE|The|the) )?%"

  # Include test files when applying the `no-unused-link` rule.
  no-unused-link/include-tests: false
