# This file serves as an example to explain various configuration parameters for
# `godoc-lint`.
#
# All keys are:
#  - Optional, unless stated otherwise.
#  - Assigned with their default value.
#

# Configuration file version.
version: "1.0"

# List of regexp patterns matching files the linter should include. When
# omitted/null, the linter includes all Go files. If assigned then only the
# files that their relative path (with respect to the config file path) matches
# any of the patterns will be processed.
include: null

# List of regexp patterns matching files the linter should skip. When
# omitted/null, the linter excludes no Go files. If assigned then only the
# files that their relative path (with respect to the config file path) does not
# match any of the patterns will be processed.
exclude: null

# List of rules to enable.
#
# See the linter docs for the list of supported rules.
enable:
  - single-pkg-doc
  - start-with-name

# List of rules to disable.
disable: null

# A map for setting individual rule options.
#
# All sub-keys are optional.
options:
  # Maximum line length for godocs, not including the `// `, or `/*` or `*/`
  # tokens.
  max-len: 77

  # The start of a valid package godoc (e.g., "Package {package-name}...").
  pkg-doc/start-with: Package

  # Skip test files when applying the `require-pkg-doc` rule.
  require-pkg-doc/skip-tests: true

  # Skip test files when applying the `require-doc` rule.
  require-doc/skip-tests: true

  # Ignore exported (public) symbols when applying the `require-doc` rule.
  require-doc/ignore-exported: false

  # Ignore unexported (private) symbols when applying the `require-doc` rule.
  require-doc/ignore-unexported: true

  # Skip test files when applying the `start-with-name` rule.
  start-with-name/skip-tests: true

  # Acceptable start pattern (regexp) for godoc starte when applying the
  # `start-with-name` rule. The `%` placeholder is where the corresponding
  # symbol name should should appear. An omitted placeholder means the symbol
  # name should appear at the end of the pattern.
  start-with-name/pattern: "((A|a|An|an|THE|The|the) )?%"
