# This file serves as an example to explain various configuration parameters for
# `godoc-lint`.
#
# All keys are:
#  - Optional, unless stated otherwise.
#  - Assigned with their default value.
#

# Configuration file version.
version: "1.0"

# List of regexp patterns matching files the linter should include. When
# omitted/null, the linter includes all Go files. If assigned then only the
# files that their absolute path matches any of the patterns will be
# processed.
include: null

# List of regexp patterns matching files the linter should skip. When
# omitted/null, the linter excludes no Go files. If assigned then only the
# files that their absolute path does not match any of the patterns will be
# processed.
exclude: null

# List of rules to enable.
#
# See the linter docs for the list of supported rules.
enable:
  - single-pkg-doc

# List of rules to disable.
disable: null

# A map for setting individual rule options.
#
# All sub-keys are optional.
options:
  # Maximum line length for godocs, not including the `// `, or `/*` or `*/`
  # tokens.
  max-length: 77

  # The start of a valid package godoc (e.g., "Package {package-name}...").
  pkg-doc/start-with: Package
