version: "2"
linters:
  default: standard
  enable:
    - godoclint
    - godot
    - intrange
    - modernize
    - testifylint
    - unconvert
  settings:
    godoclint:
      default: all
    testifylint:
      enable-all: true
      disable:
        - encoded-compare
  exclusions:
    rules:
      - path: _test\.go$
        linters:
          - godoclint
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
    gci:
      sections:
        - standard
        - default
        - localmodule
