version: "2"
linters:
  default: standard
  enable:
    - godoclint
    - godot
    - testifylint
  settings:
    godoclint:
      default: all
  exclusions:
    rules:
      - path: _test\.go$
        linters:
          - godoclint
