version: "2"
linters:
  default: standard
  enable:
    - godoclint
    - godot
    - testifylint
  settings:
    godoclint:
      default: all
    testifylint:
      enable-all: true
      disable:
        - encoded-compare
  exclusions:
    rules:
      - path: _test\.go$
        linters:
          - godoclint
