# Default configuration
version: "1.0"
enable:
  - pkg-doc
  - single-pkg-doc
  - start-with-name
options:
  max-len: 77
  pkg-doc/start-with: Package
  require-pkg-doc/include-tests: false
  require-doc/include-tests: false
  require-doc/ignore-exported: false
  require-doc/ignore-unexported: true
  start-with-name/include-tests: false
  start-with-name/pattern: "((A|a|An|an|THE|The|the) )?%"
